# -------------------------------------------------------------------------
#   _____   _   _          _____   _           _       _
#  |  ___| (_) | |   ___  |  ___| (_)   __ _  | |__   | |_    ___   _ __
#  | |_    | | | |  / _ \ | |_    | |  / _  | | '_ \  | __|  / _ \ | '__|
#  |  _|   | | | | |  __/ |  _|   | | | (_| | | | | | | |_  |  __/ | |
#  |_|     |_| |_|  \___| |_|     |_|  \__, | |_| |_|  \__|  \___| |_|
#                                      |___/
# 
# This is the FileFighter docker-compose file
# 
# DO NOT CHANGE THIS FILE DIRECTY!
# If you want to configure your instance of FileFighter edit the .env file.
#
# Starting FileFighter:
# docker-compose up -d
#
# -------------------------------------------------------------------------
version: "3.3"
services:
  frontend:
    image: filefighter/frontend:${RELEASE_CHANNEL}
    ports:
      - ${FRONTEND_PORT}:80
    depends_on:
      - fss
      - filehandler
    networks:
      - FileFighterNetwork
    restart: ${RESTART_POLICY}

  fss:
    image: filefighter/filesystemservice:${RELEASE_CHANNEL}
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_CONTAINER_NAME: db
      JWT_SECRET: ${JWT_SECRET} 
      FRONTEND_ORIGIN: ${FRONTEND_PROTOCOL}://${FRONTEND_HOST}:${FRONTEND_PORT}
      SPRING_PROFILES_ACTIVE: "prod"
    depends_on:
      - db 
    networks:
      - FileFighterNetwork
    restart: ${RESTART_POLICY}

  db:
    image: mongo:latest
    environment:
      MONGO_INITDB: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - FileFighterNetwork
    volumes:
      - ${DB_VOLUME}:/data/db
    restart: ${RESTART_POLICY}

  filehandler:
    image: filefighter/filehandler:${RELEASE_CHANNEL}
    depends_on:
      - fss
    networks:
      - FileFighterNetwork
    volumes:
      - ${FILEHANDLER_VOLUME}:/workdir
    restart: ${RESTART_POLICY}

  ftp-service:
    image: filefighter/ftp-service:${RELEASE_CHANNEL}
    environment:
      FTP_SERVICE_BACKEND_URL: http://fss:8080
      FTP_SERVICE_FILEHANDLER_URL: http://filehandler:5000
    # TODO: could be handled by the nginx
    ports:
      - "2121:2121"
      - "10000-10010:10000-10010"
    depends_on:
      - fss
      - filehandler
    networks:
      - FileFighterNetwork
    restart: ${RESTART_POLICY}

networks:
  FileFighterNetwork:
