version: "3.3"
services:
  FileFighterFrontend:
    image: filefighter/frontend:stable
    networks:
      - FileFighterNetwork
    depends_on:
      - FileFighterREST
      - FileFighterFileHandler
    ports:
      - "80:80"
  FileFighterREST:
    image: filefighter/rest:stable
    environment:
      DB_USERNAME: root
      DB_PASSWORD: GUZFDEGFIDGSZGFZGZDGSZ #change this
      DB_NAME: filefighter
      DB_CONTAINER_NAME: FileFighterDB
      SPRING_PROFILES_ACTIVE: "prod"
    expose:
      - "8080"
    depends_on:
      - FileFighterDB
    networks:
      - FileFighterNetwork
  FileFighterDB:
    image: mongo:latest
    environment:
      MONGO_INITDB: filefighter
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: GUZFDEGFIDGSZGFZGZDGSZ  #change this
    networks:
      - FileFighterNetwork
  FileFighterFileHandler:
    image: filefighter/filehandler:stable
    networks:
      - FileFighterNetwork
    depends_on:
      - FileFighterREST
networks:
  FileFighterNetwork:
