# -------------------------------------------------------------------------
#   _____   _   _          _____   _           _       _
#  |  ___| (_) | |   ___  |  ___| (_)   __ _  | |__   | |_    ___   _ __
#  | |_    | | | |  / _ \ | |_    | |  / _  | | '_ \  | __|  / _ \ | '__|
#  |  _|   | | | | |  __/ |  _|   | | | (_| | | | | | | |_  |  __/ | |
#  |_|     |_| |_|  \___| |_|     |_|  \__, | |_| |_|  \__|  \___| |_|
#                                      |___/
# 
# This is the FileFighter docker-compose file
# 
# DO NOT CHANGE THIS FILE DIRECTY!
# If you want to configure your instance of FileFighter edit the .env file.
#
# Starting FileFighter:
# docker-compose up -d
#
# -------------------------------------------------------------------------
version: "3.3"
services:
  frontend:
    image: filefighter/frontend:stable
    ports:
      - "80:80"
    depends_on:
      - fss
      - filehandler
    networks:
      - FileFighterNetwork
    restart: ${RESTART_POLICY}

  fss:
    image: filefighter/filesystemservice:stable
    environment:
      DB_USERNAME: root
      DB_PASSWORD: test
      DB_NAME: filefighter
      DB_CONTAINER_NAME: db
      JWT_SECRET: JWTs3cr3t
      FRONTEND_ORIGIN: http://localhost
      SPRING_PROFILES_ACTIVE: "prod"
    depends_on:
      - db 
    networks:
      - FileFighterNetwork
    restart: ${RESTART_POLICY}

  db:
    image: mongo:latest
    environment:
      MONGO_INITDB: filefighter
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
    networks:
      - FileFighterNetwork
    restart: ${RESTART_POLICY}

  filehandler:
    image: filefighter/filehandler:stable
    depends_on:
      - fss
    networks:
      - FileFighterNetwork
    restart: ${RESTART_POLICY}

  ftp-service:
    image: filefighter/ftp-service:stable
    environment:
      FTP_SERVICE_BACKEND_URL: http://fss:8080
      FTP_SERVICE_FILEHANDLER_URL: http://filehandler:5000
    # TODO: could be handled by the nginx
    ports:
      - "2121:2121"
      - "10000-10010:10000-10010"
    depends_on:
      - fss
      - filehandler
    networks:
      - FileFighterNetwork
    restart: ${RESTART_POLICY}

networks:
  FileFighterNetwork:
