#!/usr/bin/env bash

# changing directory to be able to use relative paths.
rootDir=$(dirname $0)
cd $rootDir

# Import necessary functions.
source lib/utils.sh
source lib/remove.sh
source lib/install.sh
source lib/start.sh
source lib/stop.sh
source lib/status.sh

version="v1.4"
date="15.11.20"

# Check if docker is running
if ! docker info >/dev/null 2>&1; then
  echo "Docker is not running, install it first or retry."
  exit 1
fi

if [ -z "$1" ]; then
  echoLogo $version $date "Show Usage"
  printUsage
  exit 1
fi

if [[ $1 == "status" ]]; then
  echoLogo $version $date "Show Status"
  ffstatus
  exit 0
fi

if [[ $1 == "install" ]]; then
  echoLogo $version $date "Installing FileFighter"
  ffinstall
  exit 0
fi

if [[ $1 == "start" ]]; then
  echoLogo $version $date "Starting FileFighter"
  ffstart
  exit 0
fi

if [[ $1 == "stop" ]]; then
  echoLogo $version $date "Stopping FileFighter"
  ffstop
  exit 0
fi

if [[ $1 == "remove" ]]; then
  echoLogo $version $date "Removing FileFighter"
  ffremove
  exit 0
fi

echoLogo $version $date "Show Usage"
printUsage
exit 1
