#!/usr/bin/env bash

# changing directory to be able to use relative paths.
SCRIPTS_LOCATION="/home/$USER/filefighter"

if [ ! -d $SCRIPTS_LOCATION ]; then
    echo "Couldn't find scripts location under '$SCRIPTS_LOCATION'."
    echo "Try reinstalling FileFighter"
    exit 1
fi


cd $SCRIPTS_LOCATION

# Import necessary functions.
source lib/utils.sh
source lib/remove.sh
source lib/install.sh
source lib/start.sh
source lib/stop.sh
source lib/status.sh
source lib/update.sh

VERSION="v1.7"
DATE="13.05.21"

# Check if docker is running
if ! docker info >/dev/null 2>&1; then
  echo "Docker is not running, install it first or retry."
  exit 1
fi

if [ -z "$1" ]; then
  echoLogo $VERSION $DATE "Show Usage"
  printUsage
  exit 1
fi

if [[ $1 == "status" ]]; then
  echoLogo $VERSION $DATE "Show Status"
  ffstatus
  exit 0
fi

if [[ $1 == "install" ]]; then
  echoLogo $VERSION $DATE "Installing FileFighter"
  ffinstall
  exit 0
fi

if [[ $1 == "start" ]]; then
  echoLogo $VERSION $DATE "Starting FileFighter"
  ffstart
  exit 0
fi

if [[ $1 == "stop" ]]; then
  echoLogo $VERSION $DATE "Stopping FileFighter"
  ffstop
  exit 0
fi

if [[ $1 == "remove" ]]; then
  echoLogo $VERSION $DATE "Removing FileFighter"
  ffremove
  exit 0
fi

if [[ $1 == "update" ]]; then
  echoLogo $VERSION $DATE "Updating FileFighter"
  ffupdate
  exit 0
fi

echoLogo $VERSION $DATE "Show Usage"
printUsage
exit 1
